apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-roles-placement
  namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
